### ISSUE TITLE
Error on Watch

### ISSUE THREAD

**Issue by fingermaster** [space150/spaceBase#50]
error scss/application.scss (Line 5 of scss/base/_widths.scss: Invalid CSS after "  1": expected ")", was ":     one-whole,")

Not sure how to take of this...

**Comment by athaeryn** [comment]
What version of Sass are you running? You'll need to use at least 3.3 (if you're using Compass, make sure you've got at least 1.0).

**Comment by fingermaster** [comment]
Sass -v 3.4.9

On Wed, Feb 4, 2015 at 11:16 AM, Mike Anderson <notifications@github.com>
wrote:

> What version of Sass are you running? You'll need to use at least 3.3 (if
> you're using Compass, make sure you've got at least 1.0).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/space150/spaceBase/issues/50#issuecomment-72884051>.
>



-- 
Peter Dillon
fingermaster@gmail.com

**Comment by fingermaster** [comment]
Ah but yes, compass 0.12.3
Every time I try to upgrade (like when trying to implement SUZY I get
massive errors and no older projects compile... sad trombone.

On Wed, Feb 4, 2015 at 11:34 AM, Peter Joseph <fingermaster@gmail.com>
wrote:

> Sass -v 3.4.9
>
> On Wed, Feb 4, 2015 at 11:16 AM, Mike Anderson <notifications@github.com>
> wrote:
>
>> What version of Sass are you running? You'll need to use at least 3.3 (if
>> you're using Compass, make sure you've got at least 1.0).
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/space150/spaceBase/issues/50#issuecomment-72884051>.
>>
>
>
>
> --
> Peter Dillon
> fingermaster@gmail.com
>



-- 
Peter Dillon
fingermaster@gmail.com
