### ISSUE TITLE
The public website should have a styleguide

### ISSUE THREAD

**Issue by albertorestifo** [space150/spaceBase#58]
I think the public website should have a styleguide, to showcase the default UI elements and document the grid.

**Comment by cstoobes** [comment]
This is our goal - to provide more substantial documentation on the public site.  In the meantime, we do have the `styleguide.html` that outlines the grid and core elements.

**Comment by cstoobes** [comment]
The styleguide is now a page on the public website: http://spacebase.space150.com/styleguide.html
